#!/bin/sh /etc/rc.common

START=120
STOP=10

USE_PROCD=1

start_service() {
    logger -t QTUN "Boot start requested"
    /etc/qtun/action/qtun.sh boot >/dev/null 2>&1 &
}

stop_service() {
    logger -t QTUN "Stop requested"
    /etc/qtun/action/qtun.sh stop >/dev/null 2>&1
}

restart_service() {
    logger -t QTUN "Restart requested"
    /etc/qtun/action/qtun.sh restart >/dev/null 2>&1
}